<a href="https://colab.research.google.com/github/Pavneet922/AgriConnect.github.io/blob/main/Train_plant_disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [14]:
print(tf.config.list_physical_devices('GPU'))

[]


In [15]:
# ! pip install -q kaggle

# from google.colab import files

# files.upload()

{}

In [16]:
# ! mkdir ~/.kaggle

# ! cp kaggle.json ~/.kaggle/

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [17]:
# ! chmod 600 ~/.kaggle/kaggle.json

In [18]:
# ! chmod 600 ~/.kaggle/kaggle.json

In [19]:
# !kaggle datasets download -d vipoooool/new-plant-diseases-dataset -p /content

Dataset URL: https://www.kaggle.com/datasets/vipoooool/new-plant-diseases-dataset
License(s): copyright-authors
new-plant-diseases-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)


In [20]:
# import zipfile
# zip_ref = zipfile.ZipFile('new-plant-diseases-dataset.zip', 'r')
# zip_ref.extractall('/content')
# zip_ref.close()

# Data Preprocessing
### Training Image Preprocessing

In [21]:
training_set = tf.keras.utils.image_dataset_from_directory(
    "/content/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train",
    labels = "inferred",
    label_mode = "categorical",
    class_names = None,
    color_mode = "rgb",
    batch_size = 32,
    image_size = (128, 128),
    shuffle = True,
    seed = None,
    validation_split = None,
    subset = None,
    interpolation = "bilinear",
    follow_links = False,
    crop_to_aspect_ratio = False,
    data_format = None
)

Found 70295 files belonging to 38 classes.


### Validation Image Preprocessing

In [22]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    "/content/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid",
    labels = "inferred",
    label_mode = "categorical",
    class_names = None,
    color_mode = "rgb",
    batch_size = 32,
    image_size = (128, 128),
    shuffle = True,
    seed = None,
    validation_split = None,
    subset = None,
    interpolation = "bilinear",
    follow_links = False,
    crop_to_aspect_ratio = False,
    data_format = None
)

Found 17572 files belonging to 38 classes.


In [23]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [24]:
for x, y in training_set:
  print(x, x.shape)
  print(y, y.shape)
  break

tf.Tensor(
[[[[127.   119.   130.  ]
   [141.   133.   144.  ]
   [124.25 116.25 127.25]
   ...
   [114.5  107.5  115.5 ]
   [110.25 103.25 111.25]
   [121.25 114.25 122.25]]

  [[136.75 128.75 139.75]
   [132.5  124.5  135.5 ]
   [131.   123.   134.  ]
   ...
   [121.   114.   122.  ]
   [116.   109.   117.  ]
   [111.5  104.5  112.5 ]]

  [[139.   131.   142.  ]
   [135.75 127.75 138.75]
   [132.   124.   135.  ]
   ...
   [120.5  113.5  121.5 ]
   [104.25  97.25 105.25]
   [114.25 107.25 115.25]]

  ...

  [[200.5  194.5  196.5 ]
   [174.5  168.5  170.5 ]
   [177.   171.   173.  ]
   ...
   [136.   124.   124.  ]
   [134.5  122.5  122.5 ]
   [129.   117.   117.  ]]

  [[188.5  182.5  184.5 ]
   [204.25 198.25 200.25]
   [182.   176.   178.  ]
   ...
   [122.   110.   110.  ]
   [133.   121.   121.  ]
   [126.25 114.25 114.25]]

  [[174.5  168.5  170.5 ]
   [179.5  173.5  175.5 ]
   [176.75 170.75 172.75]
   ...
   [144.   132.   132.  ]
   [128.   116.   116.  ]
   [129.5  117.5  11

#Building Model

In [25]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout
from tensorflow.keras.models import Sequential

In [26]:
model = Sequential()

##Building Convolution Layer

In [27]:
model.add(Conv2D(filters = 32, kernel_size=3, padding="same", activation="relu", input_shape=[128, 128, 3]))
model.add(Conv2D(filters=32, kernel_size=3, activation="relu"))
model.add(MaxPooling2D(pool_size=2, strides=2))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [28]:
model.add(Conv2D(filters = 64, kernel_size = 3, padding = "same", activation = "relu"))
model.add(Conv2D(filters = 64, kernel_size = 3, activation = "relu"))
model.add(MaxPooling2D(pool_size = 2, strides = 2))

In [29]:
model.add(Conv2D(filters = 128, kernel_size = 3, padding = "same", activation = "relu"))
model.add(Conv2D(filters = 128, kernel_size = 3, activation = "relu"))
model.add(MaxPooling2D(pool_size = 2, strides = 2))

In [30]:
model.add(Conv2D(filters = 256, kernel_size = 3, padding = "same", activation = "relu"))
model.add(Conv2D(filters = 256, kernel_size = 3, activation = "relu"))
model.add(MaxPooling2D(pool_size = 2, strides = 2))

In [31]:
model.add(Conv2D(filters = 512, kernel_size = 3, padding = "same", activation = "relu"))
model.add(Conv2D(filters = 512, kernel_size = 3, activation = "relu"))
model.add(MaxPooling2D(pool_size = 2, strides = 2))

In [32]:
model.add(Dropout(0.25)) #to avoid overshooting

In [33]:
model.add(Flatten())

In [34]:
model.add(Dense(units = 1500, activation = "relu"))

In [35]:
model.add(Dropout(0.4))

In [36]:
#Output Layer
model.add(Dense(units = 38, activation = "softmax"))

##Compiling Model

In [37]:
model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate = 0.0001), loss = "categorical_crossentropy", metrics =["accuracy"])

In [38]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 128, 128, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 126, 126, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 63, 63, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 63, 63, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 61, 61, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 30, 30, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 30, 30, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 28, 28, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 14, 14, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (None, 14, 14, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (None, 12, 12, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 6, 6, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 6, 6, 512)           │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 4, 4, 512)           │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 2, 2, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 2, 2, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 2048)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1500)                │       3,073,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 1500)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 38)                  │          57,038 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

##Model Training

In [ ]:
training_history = model.fit(x = training_set, validation_data = validation_set, epochs = 10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 10350s 5s/step - accuracy: 0.3897 - loss: 2.1677 - val_accuracy: 0.8292 - val_loss: 0.5456
Epoch 2/10
1405/2197 ━━━━━━━━━━━━━━━━━━━━ 58:38 4s/step - accuracy: 0.8093 - loss: 0.6034

#Model Evaluation

In [ ]:
#Model evaluation on Training set
train_loss, train_acc = model.evaluate(training_set)

In [ ]:
print(train_loss, train_acc)

In [ ]:
#Model evaluation on Training set
val_loss, val_acc = model.evaluate(validation_set)

In [ ]:
print(val_loss, val_acc)

#Saving Model

In [ ]:
model.save("trained_model.keras") #or "trained_model.h5" then the size will be very large. Keras is better

In [ ]:
training_history.history

In [ ]:
#Recording history in json
import json
with open("training_history.json", "w") as f:
  json.dump(training_history.history, f)

#Accuracy Visualization

In [ ]:
epochs = [i for i in range(1, 11)]
plt.plot(epochs, training_history.history["accuracy"], color = "red", label = "Training accuracy")
plt.plot(epochs, training_history.history["accuracy"], color = "blue", label = "Validation accuracy")
plt.xlabel("No. of epochs")
plt.ylabel("Accuracy result")
plt.title("Visualization of accuracy result")
plt.legend()
plt.show()

##Some other matrix for model evaluation

In [ ]:
class_name = validation_set.class_names
class_name

In [ ]:
test_set = tf.keras.utils.image_dataset_from_directory(
    "/content/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid",
    labels = "inferred",
    label_mode = "categorical",
    class_names = None,
    color_mode = "rgb",
    batch_size = 32,
    image_size = (128, 128),
    shuffle = False,
    seed = None,
    validation_split = None,
    subset = None,
    interpolation = "bilinear",
    follow_links = False,
    crop_to_aspect_ratio = False,
    data_format = None)

In [ ]:
y_pred = model.predict(test_set)
y_pred, y_pred.shape

In [ ]:
predicted_categories = tf.argmax(y_pred, axis = 1)
predicted_categories

In [ ]:
true_categories = tf.concat([y for x, y in test_set], axis = 0)
true_categories

In [ ]:
y_true = tf.argmax(true_categories, axis = 1)
y_true

In [ ]:
from sklearn.metrics import classification_report
classification_report(y_true, predicted_categories, target_names = class_name)

In [ ]:
cm = confusion_matrix(y_true, predicted_categories)
cm

##Confusion Matrix Visualaziation

In [ ]:
plt.figure(figsize = (40, 40))
sns.heatmap(cm, annot = True )
plt.xlabel("Predicted class")
plt.ylabel("Actual class")
plt.title("Plant disease prediction confusion matrix")
plt.show()